# Use postgres/example user/password credentials
version: '3.1'

services:

  arangodb:
    image: arangodb:3.12
    ports:
      - "8529:8529"
    environment:
#      ARANGO_ROOT_PASSWORD: changeme
      ARANGO_NO_AUTH: "1"
    volumes:
      - arango-data:/var/lib/arangodb3

  pm:
    depends_on:
      - arangodb
      - redpanda
    image: ghcr.io/hpcclab/oaas/package-manager
    build:
      context: package-manager
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8088:8080"
    environment:
      QUARKUS_CONSOLE_COLOR: 'true'
      QUARKUS_HTTP_CORS: 'true'
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      OPRC_PM_KAFKAENABLED: 'true'
      OPRC_DB_PKG_HOST: arangodb
      OPRC_DB_PKG_PORT: "8529"
      OPRC_DB_PKG_DB: oaas
      OPRC_DB_PKG_USER: root
      OPRC_DB_PKG_PASS: changeme
    restart: on-failure
    healthcheck: &oaas-healthcheck
      test: curl --fail http://localhost:8080/q/health || exit 1
      interval: 10s
      retries: 5
      timeout: 10s


  crm:
    build:
      context: class-runtime-manager
      dockerfile: src/main/docker/Dockerfile.jvm
    image: ghcr.io/hpcclab/oaas/class-runtime-manager
    deploy:
      replicas: 0
    healthcheck: *oaas-healthcheck

volumes:
  minio-data:
  arango-data:
