
"%dev":
  quarkus:
    http:
      port: 8091
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
    kubernetes-client:
      namespace: oaas
  oprc:
    env: |
      OPRC_DB_PKG_HOST=arango-cluster
      OPRC_DB_PKG_PORT=8529
      OPRC_DB_PKG_USER=root
      OPRC_DB_PKG_DB=oaas
      OPRC_DB_DEFAULT_HOST=arango-cluster
      OPRC_DB_DEFAULT_PORT=8529
      OPRC_DB_DEFAULT_DB=oaas
      OPRC_DB_DEFAULT_USER=root
      OPRC_DB_S3DEFAULT_URL=http://minio.oaas.svc.cluster.local
      OPRC_DB_S3DEFAULT_BUCKET=oaas-bkt
      OPRC_DB_S3DEFAULT_PUBLICURL=http://s3.127.0.0.1.nip.io:9090
      OPRC_DB_S3DEFAULT_USER=minio_access_key
      OPRC_DB_S3DEFAULT_PASS=minio_secret_key
    envconf:
      kafka: "oaas-kafka-bootstrap:9092"
      pmHost: localhost
      pmPort: 8088
    crm:
      monitorDisable: true
      managedEnv: |
        - id: 1
          name: cloud-1
          kubeContext: cc
          availability:
            uptimePercentage: 0.99
        - id: 2
          name: cloud-2
          kubeContext: cc
          availability:
            uptimePercentage: 0.99
        - id: 3
          name: edge-0
          kubeContext: cc2
          namespace: oaas-0
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-0
        - id: 4
          name: edge-1
          kubeContext: cc2
          namespace: oaas-1
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-1
        - id: 5
          name: edge-2
          kubeContext: cc2
          namespace: oaas-2
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-2
        - id: 6
          name: edge-3
          kubeContext: cc2
          namespace: oaas-3
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-3
        - id: 7
          name: edge-4
          kubeContext: cc2
          namespace: oaas-4
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-4
        - id: 8
          name: edge-5
          kubeContext: cc2
          namespace: oaas-5
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-5
        - id: 9
          name: edge-6
          kubeContext: cc2
          namespace: oaas-6
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-6
        - id: 10
          name: edge-7
          kubeContext: cc2
          namespace: oaas-7
          availability:
            uptimePercentage: 0.99
          nodeSelector:
            kubernetes.io/hostname: k3d-k3s-default-agent-7
"%test":
  oprc:
    crm:
      loadTemplateOnStart: false
      managedEnv: default

oprc:
  crm:
    exposeKnative: false
    pmHost: localhost
    pmPort: 8088
    promUrl: localhost:9090
  log: INFO
  name: class-runtime-manager
  envconf:
    kafka: "localhost:9092"
    pmHost: ${oprc.crm.pmHost}
    pmPort: ${oprc.crm.pmPort}

quarkus:
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oprc.log}
  http:
    access-log:
      enabled: true
      exclude-pattern: /q/.*
  native:
    resources:
      includes:
        - crts.yml
        - crts/**
  vertx:
    prefer-native-transport: true
  container-image:
    builder: docker
    image: ${ci.registry.image:oaas}/${oprc.name}${tag:}
  console:
    color: true
  grpc:
    clients:
      package-manager:
        use-quarkus-grpc-client: true
        host: ${oprc.crm.pmHost}
        port: ${oprc.crm.pmPort}

    server:
      enable-reflection-service: true
      use-separate-server: false
