"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
  oprc:
    log: TRACE
    pm:
      crmEnabled: false
      kafkaEnabled: false
      env: |
        defaultEnv: default
        environments:
        - name: default
          crmUrl: http://localhost:8091

"%dev":
  quarkus:
    console:
      color: true
    http:
      port: 8088
  oprc:
    log: DEBUG
    pm:
      crmEnabled: false
      kafkaEnabled: false
      env: |
          defaultEnv: cloud-1
          environments:
          - name: cloud-1
            id: 1
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: cloud-2
            id: 2
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-0
            id: 3
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-1
            id: 4
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-2
            id: 5
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-3
            id: 6
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-4
            id: 7
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-5
            id: 8
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-6
            id: 9
            crmUrl: http://localhost:8091
            availability: 0.99
          - name: edge-7
            id: 10
            crmUrl: http://localhost:8091
            availability: 0.99
  kafka:
    bootstrap:
      servers: localhost:31000


oprc:
  pm:
    clsProvisionTopic: oaas-cls
    kafkaEnabled: true
    crmEnabled: true
    fnProvisionTopic: oaas-fn
    crHashTopic: oaas-cr-hash
  log: INFO
  name: package-manager
  env: |
    OPRC_DB_PKG_HOST=127.0.0.1
    OPRC_DB_PKG_PORT=8529
    OPRC_DB_PKG_USER=root
    OPRC_DB_PKG_DB=oaas


quarkus:
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/package-manager
    enable: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oprc.log}
  container-image:
    builder: docker
    image: ${ci.registry.image:oaas}/${oprc.name}${tag:}
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**

  kafka:
    devservices:
      enabled: false
  grpc:
    server:
      enable-reflection-service: true
      use-separate-server: false
mp:
  messaging:
    outgoing:
      fnProvisions:
        enabled: ${oprc.pm.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oprc.pm.fnProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      clsProvisions:
        enabled: ${oprc.pm.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oprc.pm.clsProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      crHashs:
        enabled: ${oprc.pm.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oprc.pm.crHashTopic}
#        value:
#          serializer: io.quarkus.kafka.client.serialization.BufferSerializer

